Repository rainbow-me/rainbowkit, pull requests merged in 2023-08, with the labels that each got.

#1442 chore: fix linting
  packages/rainbowkit/src/wallets/walletConnectors/safeWallet/safeWallet.ts
Labels: ready to merge

#1429 chore: refresh custom chains docs
  site/data/docs/custom-chains.mdx
Labels: ready to merge

#1435 chore: upgrade vite @vitejs/plugin-react in examples
  examples/with-vite/package.json
  pnpm-lock.yaml
Labels: ready to merge

#1447 feat: example projectId
  .changeset/modern-pets-beg.md
  .github/workflows/ci.yml
  packages/rainbowkit/src/wallets/getWalletConnectConnector.ts
Labels: ready to merge

#1414 chore: upgrade next-auth to >=4.21.0
  .changeset/ninety-bottles-behave.md
  examples/with-next-siwe-next-auth/package.json
  examples/with-next-siwe-next-auth/pages/api/auth/[...nextauth].ts
  package.json
  packages/example/package.json
  packages/example/pages/api/auth/[...nextauth].ts
  packages/rainbowkit-siwe-next-auth/package.json
  pnpm-lock.yaml
Labels: ready to merge

#1474 feat: version fingerprinting for debugging
  package.json
  packages/rainbowkit/build.js
  packages/rainbowkit/src/components/RainbowKitProvider/RainbowKitProvider.tsx
  packages/rainbowkit/src/components/RainbowKitProvider/useFingerprint.ts
  pnpm-lock.yaml
Labels: ready to merge

#1452 chore: base network examples and templates
  .changeset/two-moles-poke.md
  examples/with-create-react-app/src/index.tsx
  examples/with-next-app/app/providers.tsx
  examples/with-next-custom-button/pages/_app.tsx
  examples/with-next-siwe-iron-session/pages/_app.tsx
  examples/with-next-siwe-next-auth/pages/_app.tsx
  examples/with-next/pages/_app.tsx
  examples/with-remix/app/root.tsx
  examples/with-vite/src/main.tsx
  packages/create-rainbowkit/generated-test-app/pages/_app.tsx
  packages/create-rainbowkit/templates/next-app/pages/_app.tsx
  packages/rainbowkit/test/index.tsx
  site/components/Provider/Provider.tsx
  site/data/docs/installation.mdx
Labels: ready to merge

#1473 feat: uniswapWallet connector
  .changeset/eighty-baboons-fold.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/uniswapWallet/uniswapWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/uniswapWallet/uniswapWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1477 feat: frameWallet support
  .changeset/happy-buckets-knock.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/frameWallet/frameWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/frameWallet/frameWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
Labels: connector

#1464 feat: bifrostWallet support
  .changeset/calm-lemons-leave.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/bifrostWallet/bifrostWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/bifrostWallet/bifrostWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1393 feat: coin98Wallet support
  .changeset/forty-carrots-marry.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/coin98Wallet/coin98Wallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/coin98Wallet/coin98Wallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: bug, connector

#1419 feat: enkryptWallet support
  .changeset/good-gifts-crash.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/enkryptWallet/enkryptWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/enkryptWallet/enkryptWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: bug, connector

#1455 feat: onekeyWallet support
  .changeset/ninety-meals-drum.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/oneKeyWallet/oneKeyWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/oneKeyWallet/oneKeyWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector
