Repository rainbow-me/rainbowkit, pull requests merged in 2023-03, with the labels that each got.

#1057 chore: update Polygon icon (polygon.svg)
  packages/rainbowkit/src/components/RainbowKitProvider/chainIcons/polygon.svg
Labels: ready to merge

#1053 feat: base goerli chain support
  .changeset/calm-seahorses-pay.md
  examples/with-create-react-app/package.json
  examples/with-next-custom-button/package.json
  examples/with-next-mint-nft/package.json
  examples/with-next-siwe-iron-session/package.json
  examples/with-next-siwe-next-auth/package.json
  examples/with-next/package.json
  examples/with-remix/package.json
  examples/with-vite/package.json
  package.json
  packages/create-rainbowkit/generated-test-app/package.json
  packages/create-rainbowkit/templates/next-app/package.json
  packages/example/package.json
  packages/example/pages/_app.tsx
  packages/rainbowkit/package.json
  packages/rainbowkit/src/components/RainbowKitProvider/chainIcons/base.svg
  packages/rainbowkit/src/components/RainbowKitProvider/provideRainbowKitChains.ts
  pnpm-lock.yaml
  site/package.json
Labels: ready to merge

#1073 feat: mew wallet support
  .changeset/cuddly-jars-breathe.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/mewWallet/mewWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/mewWallet/mewWallet.ts
  pnpm-lock.yaml
  site/data/docs/custom-wallet-list.mdx
Labels: ready to merge

#1029 feat: bitski extension support
  .changeset/tasty-timers-look.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/bitskiWallet/bitskiWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/bitskiWallet/bitskiWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector, ready to merge

#1080 fix: shimDisconnect option passthrough
  .changeset/blue-gifts-hunt.md
  packages/rainbowkit/src/wallets/walletConnectors/bitskiWallet/bitskiWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/braveWallet/braveWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/coinbaseWallet/coinbaseWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/injectedWallet/injectedWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/metaMaskWallet/metaMaskWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/mewWallet/mewWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/rainbowWallet/rainbowWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/trustWallet/trustWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: ready to merge

#1046 fix: treating ipad as small ios to enable mobile deep linking
  .changeset/stupid-swans-type.md
  packages/rainbowkit/src/utils/isMobile.ts
Labels: ready to merge

#1102 fix: injectedWallet fallback detection improvement
  .changeset/weak-berries-rest.md
  packages/rainbowkit/src/wallets/Wallet.ts
  packages/rainbowkit/src/wallets/connectorsForWallets.test.ts
  packages/rainbowkit/src/wallets/connectorsForWallets.ts
  packages/rainbowkit/src/wallets/walletConnectors/injectedWallet/injectedWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/metaMaskWallet/metaMaskWallet.ts
Labels: ready to merge

#1104 feat: updated injectedWallet name and icon
  .changeset/large-numbers-fetch.md
  packages/rainbowkit/src/wallets/connectorsForWallets.test.ts
  packages/rainbowkit/src/wallets/walletConnectors/injectedWallet/injectedWallet.png
  packages/rainbowkit/src/wallets/walletConnectors/injectedWallet/injectedWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/injectedWallet/injectedWallet.ts
Labels: ready to merge

#1028 feat: safe connector
  .changeset/cold-camels-visit.md
  packages/example/pages/_app.tsx
  packages/example/public/favicon.ico
  packages/example/public/manifest.json
  packages/example/public/rainbow.svg
  packages/rainbowkit/src/wallets/getDefaultWallets.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/safeWallet/safeWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/safeWallet/safeWallet.ts
Labels: enhancement, ready to merge

#1127 docs: added safeWallet to custom wallet list
  site/data/docs/custom-wallet-list.mdx
Labels: ready to merge

#1126 docs: update manual installation docs to include correct ethers version
  site/data/docs/installation.mdx
Labels: ready to merge

#1124 fix: arbitrum goerli icon, deprecate rinkeby
  packages/rainbowkit/src/components/RainbowKitProvider/provideRainbowKitChains.ts
Labels: ready to merge

#1107 feat: okxWallet
  .changeset/thin-turkeys-shave.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/okxWallet/okxWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/okxWallet/okxWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: ready to merge

#1077 feat: tahoWallet
  .changeset/spotty-badgers-grin.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/tahoWallet/tahoWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/tahoWallet/tahoWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: ready to merge

#1106 feat: dawnWallet
  .changeset/violet-eyes-battle.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/dawnWallet/dawnWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/dawnWallet/dawnWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: ready to merge

#1108 feat: zerionWallet
  .changeset/many-schools-deliver.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/zerionWallet/zerionWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/zerionWallet/zerionWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: ready to merge
