Repository rainbow-me/rainbowkit, pull requests merged in 2023-07, with the labels that each got.

#1375 fix: metamask deep link in 0.12.x
  .changeset/early-carrots-train.md
  packages/rainbowkit/src/wallets/walletConnectors/metaMaskWallet/metaMaskWallet.ts
Labels: ready to merge

#1372 fix: metamask deep link
  .changeset/rich-mugs-occur.md
  packages/rainbowkit/src/wallets/walletConnectors/metaMaskWallet/metaMaskWallet.ts
Labels: ready to merge

#1287 feat: cronos blockchain icon
  .changeset/eight-wombats-appear.md
  packages/rainbowkit/src/components/RainbowKitProvider/chainIcons/cronos.svg
  packages/rainbowkit/src/components/RainbowKitProvider/provideRainbowKitChains.ts
Labels: ready to merge

#1344 chore: update phantom wallet logo
  packages/rainbowkit/src/wallets/walletConnectors/phantomWallet/phantomWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/phantomWallet/phantomWallet.ts
Labels: ready to merge

#1351 fix: default projectId for example and docs site
  packages/example/pages/_app.tsx
  site/components/Provider/Provider.tsx
Labels: ready to merge

#1369 example: with-next-app webpack externals config
  examples/with-next-app/next.config.js
  examples/with-next-app/package.json
  pnpm-lock.yaml
  site/data/docs/installation.mdx
Labels: ready to merge

#1370 test: chain modal component unit tests
  .github/workflows/ci.yml
  examples/with-create-react-app/package.json
  examples/with-next-app/package.json
  examples/with-next-custom-button/package.json
  examples/with-next-mint-nft/package.json
  examples/with-next-siwe-iron-session/package.json
  examples/with-next-siwe-next-auth/package.json
  examples/with-next/package.json
  examples/with-remix/package.json
  examples/with-vite/package.json
  package.json
  packages/create-rainbowkit/generated-test-app/package.json
  packages/create-rainbowkit/templates/next-app/package.json
  packages/example/package.json
  packages/example/pages/_app.tsx
  packages/rainbowkit/package.json
  packages/rainbowkit/src/components/ChainModal/ChainModal.test.tsx
  packages/rainbowkit/test/index.tsx
  packages/rainbowkit/test/setup.ts
  packages/rainbowkit/tsconfig.json
  pnpm-lock.yaml
  site/components/Provider/Provider.tsx
  site/package.json
  vitest.config.ts
Labels: ready to merge

#1156 fix: only display provided chains in ChainModal
  .changeset/dirty-papayas-walk.md
  packages/rainbowkit/src/components/ChainModal/ChainModal.test.tsx
  packages/rainbowkit/src/components/ChainModal/ChainModal.tsx
Labels: ready to merge

#1381 fix: legacy connector type safety
  packages/rainbowkit/src/wallets/walletConnectors/rainbowWallet/rainbowWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/trustWallet/trustWallet.ts
Labels: ready to merge

#1166 feat: safeheronWallet support
  .changeset/shaggy-cameras-marry.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/safeheronWallet/safeheronWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/safeheronWallet/safeheronWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: bug, connector

#1041 feat: frontierWallet support
  .changeset/short-follow-clap.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/frontierWallet/frontierWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/frontierWallet/frontierWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: bug, connector

#1283 feat: tokenPocket support
  .changeset/ten-teachers-agree.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/tokenPocketWallet/tokenPocketWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/tokenPocketWallet/tokenPocketWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1295 feat: coreWallet support
  .changeset/khaki-insects-mix.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/coreWallet/coreWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/coreWallet/coreWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1396 feat: walletconnect connector attribution
  packages/rainbowkit/src/wallets/walletConnectors/rainbowWallet/rainbowWallet.ts
Labels: ready to merge
