Repository rainbow-me/rainbowkit, pull requests merged in 2023-10, with the labels that each got.

#1536 feat: add bitgetWallet, deprecate bitKeepWallet
  .changeset/rich-dolls-walk.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/bitKeepWallet/bitKeepWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/bitgetWallet/bitgetWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/bitgetWallet/bitgetWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1541 feat: show status of connect modal in example dApp
  packages/example/pages/index.tsx
Labels: ready to merge

#1504 feat: zealWallet support
  .changeset/ten-goats-thank.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/locales/en_US.json
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/metaMaskWallet/metaMaskWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/zealWallet/zealWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/zealWallet/zealWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1506 feat: safepalWallet support
  .changeset/cool-spiders-return.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/locales/en_US.json
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/safepalWallet/safepalWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/safepalWallet/safepalWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1571 docs: fix media-kit url
  site/pages/index.tsx
Labels: ready to merge

#1565 feat: desigWallet support
  .changeset/wild-cameras-kick.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/locales/en_US.json
  packages/rainbowkit/src/wallets/walletConnectors/desigWallet/desigWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/desigWallet/desigWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1563 feat: clvWallet support
  .changeset/tidy-experts-sell.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/locales/en_US.json
  packages/rainbowkit/src/wallets/walletConnectors/clvWallet/clvWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/clvWallet/clvWallet.ts
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector

#1403 feat: oktoWallet support
  .changeset/nine-pets-design.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/locales/en_US.json
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/oktoWallet/oktoWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/oktoWallet/oktoWallet.ts
  site/data/docs/custom-wallet-list.mdx
Labels: connector, blocked

#1581 fix: siwe signature request button label
  packages/rainbowkit/src/locales/en_US.json
Labels: ready to merge

#1582 fix: ethereum.providers support for coinbaseWallet
  .changeset/little-panthers-cough.md
  packages/rainbowkit/src/wallets/walletConnectors/coinbaseWallet/coinbaseWallet.ts
Labels: ready to merge

#1583 fix: trustWallet detection mobile in-app browser
  .changeset/brown-elephants-rule.md
  packages/rainbowkit/src/wallets/walletConnectors/trustWallet/trustWallet.ts
Labels: ready to merge

#1579 chore: update i18n translations
  crowdin.yml
  packages/rainbowkit/src/locales/ar_AR.json
  packages/rainbowkit/src/locales/es_419.json
  packages/rainbowkit/src/locales/fr_FR.json
  packages/rainbowkit/src/locales/hi_IN.json
  packages/rainbowkit/src/locales/id_ID.json
  packages/rainbowkit/src/locales/ja_JP.json
  packages/rainbowkit/src/locales/ko_KR.json
  packages/rainbowkit/src/locales/pt_BR.json
  packages/rainbowkit/src/locales/ru_RU.json
  packages/rainbowkit/src/locales/th_TH.json
  packages/rainbowkit/src/locales/tr_TR.json
  packages/rainbowkit/src/locales/zh_CN.json
Labels: ready to merge

#1233 feat: add desktop download URL and instructions
  .changeset/wise-doors-give.md
  packages/rainbowkit/package.json
  packages/rainbowkit/src/components/ConnectOptions/ConnectDetails.tsx
  packages/rainbowkit/src/components/ConnectOptions/DesktopOptions.tsx
  packages/rainbowkit/src/components/Icons/Connect.tsx
  packages/rainbowkit/src/components/Icons/Linux.svg
  packages/rainbowkit/src/components/Icons/Macos.svg
  packages/rainbowkit/src/components/Icons/Windows.svg
  packages/rainbowkit/src/components/Icons/connect.svg
  packages/rainbowkit/src/locales/en_US.json
  packages/rainbowkit/src/utils/platforms.ts
  packages/rainbowkit/src/wallets/Wallet.ts
  packages/rainbowkit/src/wallets/downloadUrls.ts
  packages/rainbowkit/src/wallets/useWalletConnectors.ts
  packages/rainbowkit/src/wallets/walletConnectors/ledgerWallet/ledgerWallet.ts
  pnpm-lock.yaml
  site/data/docs/custom-wallets.mdx
Labels: enhancement

#1590 chore: update i18n translations
  packages/rainbowkit/src/locales/ar_AR.json
  packages/rainbowkit/src/locales/es_419.json
  packages/rainbowkit/src/locales/fr_FR.json
  packages/rainbowkit/src/locales/hi_IN.json
  packages/rainbowkit/src/locales/id_ID.json
  packages/rainbowkit/src/locales/ja_JP.json
  packages/rainbowkit/src/locales/ko_KR.json
  packages/rainbowkit/src/locales/pt_BR.json
  packages/rainbowkit/src/locales/ru_RU.json
  packages/rainbowkit/src/locales/th_TH.json
  packages/rainbowkit/src/locales/tr_TR.json
  packages/rainbowkit/src/locales/zh_CN.json
Labels: ready to merge
