Repository rainbow-me/rainbowkit, pull requests merged in 2023-11, with the labels that each got.

#1595 docs: fix missing en-US localization docs
  site/data/en-US/docs/localization.mdx
Labels: ready to merge

#1594 fix: remove invalid localeDetection type from example's next.config
  examples/with-next/next.config.js
  packages/example/next.config.js
  site/data/ar/docs/localization.mdx
  site/data/es-419/docs/localization.mdx
  site/data/fr/docs/localization.mdx
  site/data/hi/docs/localization.mdx
  site/data/id/docs/localization.mdx
  site/data/ja/docs/localization.mdx
  site/data/ko/docs/localization.mdx
  site/data/pt-BR/docs/localization.mdx
  site/data/ru/docs/localization.mdx
  site/data/th/docs/localization.mdx
  site/data/tr/docs/localization.mdx
  site/data/zh-CN/docs/localization.mdx
  site/next.config.js
Labels: ready to merge

#1593 fix: codesandbox devcontainers
  examples/with-create-react-app/.codesandbox/tasks.json
  examples/with-create-react-app/.devcontainer/devcontainer.json
  examples/with-create-react-app/package.json
  examples/with-next-app-i18n/.codesandbox/tasks.json
  examples/with-next-app-i18n/.devcontainer/devcontainer.json
  examples/with-next-app/.codesandbox/tasks.json
  examples/with-next-app/.devcontainer/devcontainer.json
  examples/with-next-custom-button/.codesandbox/tasks.json
  examples/with-next-custom-button/.devcontainer/devcontainer.json
  examples/with-next-mint-nft/.codesandbox/tasks.json
  examples/with-next-mint-nft/.devcontainer/devcontainer.json
  examples/with-next-mint-nft/pages/index.tsx
  examples/with-next-siwe-iron-session/.codesandbox/tasks.json
  examples/with-next-siwe-iron-session/.devcontainer/devcontainer.json
  examples/with-next-siwe-next-auth/.codesandbox/tasks.json
  examples/with-next-siwe-next-auth/.devcontainer/devcontainer.json
  examples/with-next/.codesandbox/tasks.json
  examples/with-next/.devcontainer/devcontainer.json
  examples/with-remix/.codesandbox/tasks.json
  examples/with-remix/.devcontainer/devcontainer.json
  examples/with-vite/.codesandbox/tasks.json
  examples/with-vite/.devcontainer/devcontainer.json
Labels: ready to merge

#1604 feat: xdc and xdcTestnet chain icons
  packages/rainbowkit/src/components/RainbowKitProvider/chainIcons/xdc.svg
  packages/rainbowkit/src/components/RainbowKitProvider/provideRainbowKitChains.ts
Labels: chain

#1596 feat: tokenaryWallet support
  .changeset/chilled-bugs-agree.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/wallets/walletConnectors/index.ts
  packages/rainbowkit/src/wallets/walletConnectors/tokenaryWallet/tokenaryWallet.svg
  packages/rainbowkit/src/wallets/walletConnectors/tokenaryWallet/tokenaryWallet.ts
  site/data/en-US/docs/custom-wallet-list.mdx
Labels: connector

#1617 fix: next-auth adapter app router safety
  .changeset/angry-kings-stare.md
  packages/rainbowkit-siwe-next-auth/build.js
Labels: ready to merge

#1618 chore: next-auth upgrade, peer version compatibility for v5
  .changeset/sixty-beans-taste.md
  examples/with-next-siwe-next-auth/package.json
  package.json
  packages/example/package.json
  packages/example/pages/api/auth/[...nextauth].ts
  packages/rainbowkit-siwe-next-auth/package.json
  pnpm-lock.yaml
Labels: ready to merge

#1619 chore: upgrade dependencies
  .changeset/four-buses-attack.md
  examples/with-create-react-app/package.json
  examples/with-next-app-i18n/package.json
  examples/with-next-app/package.json
  examples/with-next-custom-button/package.json
  examples/with-next-mint-nft/package.json
  examples/with-next-siwe-iron-session/package.json
  examples/with-next-siwe-next-auth/package.json
  examples/with-next/package.json
  examples/with-remix/package.json
  examples/with-vite/package.json
  package.json
  packages/create-rainbowkit/generated-test-app/package.json
  packages/create-rainbowkit/templates/next-app/package.json
  packages/example/package.json
  packages/rainbowkit/package.json
  pnpm-lock.yaml
  site/package.json
Labels: ready to merge

#1624 chore: upgrade pnpm packageManager version
  package.json
Labels: ready to merge

#1623 site: fix sitemap lastmod consistency
  site/next-sitemap.config.js
  site/public/sitemap-0.xml
Labels: ready to merge

#1621 feat: sepolia testnet support
  .changeset/quick-numbers-bathe.md
  packages/example/pages/_app.tsx
  packages/rainbowkit/src/components/RainbowKitProvider/provideRainbowKitChains.ts
Labels: ready to merge

#1629 docs: deprecate walletconnect v2 announcement banner
  site/data/ar/docs/introduction.mdx
  site/data/en-US/docs/introduction.mdx
  site/data/es-419/docs/introduction.mdx
  site/data/fr/docs/introduction.mdx
  site/data/hi/docs/introduction.mdx
  site/data/id/docs/introduction.mdx
  site/data/ja/docs/introduction.mdx
  site/data/ko/docs/introduction.mdx
  site/data/pt-BR/docs/introduction.mdx
  site/data/ru/docs/introduction.mdx
  site/data/th/docs/introduction.mdx
  site/data/tr/docs/introduction.mdx
  site/data/zh-CN/docs/introduction.mdx
Labels: ready to merge

#1630 docs: rainbow-button readme and contributing guide
  .github/CONTRIBUTING.md
  packages/rainbow-button/README.md
Labels: ready to merge

#1631 docs: legacy cleanup
  examples/with-next-rainbow-button/pages/_app.tsx
  examples/with-next-wallet-button/pages/_app.tsx
  packages/rainbow-button/CHANGELOG.md
  packages/rainbowkit/CHANGELOG.md
  site/data/ar/docs/custom-chains.mdx
  site/data/ar/docs/installation.mdx
  site/data/en-US/docs/custom-chains.mdx
  site/data/en-US/docs/installation.mdx
  site/data/en-US/guides/rainbow-button.mdx
  site/data/es-419/docs/custom-chains.mdx
  site/data/es-419/docs/installation.mdx
  site/data/fr/docs/custom-chains.mdx
  site/data/fr/docs/installation.mdx
  site/data/hi/docs/custom-chains.mdx
  site/data/hi/docs/installation.mdx
  site/data/id/docs/custom-chains.mdx
  site/data/id/docs/installation.mdx
  site/data/ja/docs/custom-chains.mdx
  site/data/ja/docs/installation.mdx
  site/data/ko/docs/custom-chains.mdx
  site/data/ko/docs/installation.mdx
  site/data/pt-BR/docs/custom-chains.mdx
  site/data/pt-BR/docs/installation.mdx
  site/data/ru/docs/custom-chains.mdx
  site/data/ru/docs/installation.mdx
  site/data/th/docs/custom-chains.mdx
  site/data/th/docs/installation.mdx
  site/data/tr/docs/custom-chains.mdx
  site/data/tr/docs/installation.mdx
  site/data/zh-CN/docs/custom-chains.mdx
  site/data/zh-CN/docs/installation.mdx
Labels: ready to merge
